services:
  php:
    build:
      context: ./php
    container_name: containernamebilemophp
    working_dir: /var/www
    ports:
      - 8496:80
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./app:/var/www

  database:
    image: mysql:8.0
    container_name: containernamebilemoapidb
    environment:
      MYSQL_ROOT_PASSWORD: bilemo_root_password
      MYSQL_DATABASE: bilemo_the_db
      MYSQL_USER: bilemo_the_user_db
      MYSQL_PASSWORD: bilemo_the_password
    ports:
      - "4436:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: containernamebilemophpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: bilemo_root_password
    ports:
      - 8495:80
    depends_on:
      - database

volumes:
  mysql_data:
